### ISSUE TITLE
【Q】疑问 望解答

### ISSUE THREAD

**Issue by newives** [Cc-Edit/CcClip#2]
请问作者 
https://github.com/Cc-Edit/CcClip/blob/master/public/ffmpeg/ffmpeg-core.wasm 这个文件是如何生成的呢

**Comment by Cc-Edit** [comment]
这个文件来自： https://github.com/ffmpegwasm/ffmpeg.wasm

**Comment by Cc-Edit** [comment]
release 版本： https://github.com/ffmpegwasm/ffmpeg.wasm-core/releases

**Comment by Cc-Edit** [comment]
编译过程有对应的文章， 知乎有翻译后的：
https://jeromewu.github.io/build-ffmpeg-webassembly-version-part-1-preparation/
https://jeromewu.github.io/build-ffmpeg-webassembly-version-part-2-compile-with-emscripten/
https://jeromewu.github.io/build-ffmpeg-webassembly-version-part-3-v0.1/
https://jeromewu.github.io/build-ffmpeg-webassembly-version-part-4-v0.2/
