### ISSUE TITLE
【Q】视频抽帧太慢，视频时长越长越慢，怎么解决

### ISSUE THREAD

**Issue by veagxxx** [Cc-Edit/CcClip#24]

**Comment by Cc-Edit** [comment]
目前的方案是对视频抽取全部帧，然后播放。所以分辨率、时长、fps都会导致抽帧时长增加。

**Comment by Cc-Edit** [comment]
基于目前的抽帧方案，按需抽帧，播放同时抽帧也许是一个可行的方案。但还是很吃设备性能。如果抛弃抽帧方案，通过流播放的方案效果会更好
